name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Run original tests
        run: pnpm run test:original

      - name: Build DXT
        run: pnpm run build:dxt

      - name: Check built files
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.d.ts
          test -f dist/run_mcp.js
