name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build

      - name: Build DXT
        run: pnpm run build:dxt

      - name: Pack DXT
        run: |
          # Always use zip to create DXT package for now
          # The dxt npm package has compatibility issues with Node.js v22
          echo "Creating DXT package with zip..."
          zip -r readability-${{ github.ref_name }}.dxt \
            dist/ \
            src/ \
            package.json \
            README.md \
            LICENSE \
            cli.js \
            -x "*.test.*" -x "*/__tests__/*" -x "*.test.ts" -x "*.test.js"

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag_name="${{ github.ref_name }}"
          dxt_file=$(ls -1 *.dxt | head -n 1)

          gh release create "$tag_name" \
            --title "Release $tag_name" \
            --generate-notes \
            "$dxt_file"
